name: aifeval
channels:
  - anaconda
  - pytorch
  - huggingface
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - abseil-cpp=20211102.0=hd4dd3e8_0
  - aiohttp=3.9.3=py311h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - annotated-types=0.6.0=py311h06a4308_0
  - anthropic=0.30.0=pyhd8ed1ab_0
  - antlr-python-runtime=4.9.3=pyhd8ed1ab_1
  - arrow-cpp=14.0.2=h374c478_1
  - asttokens=2.4.1=pyhd8ed1ab_0
  - autoflake=1.7.5=pyhd8ed1ab_0
  - aws-c-auth=0.6.19=h5eee18b_0
  - aws-c-cal=0.5.20=hdbd6064_0
  - aws-c-common=0.8.5=h5eee18b_0
  - aws-c-compression=0.2.16=h5eee18b_0
  - aws-c-event-stream=0.2.15=h6a678d5_0
  - aws-c-http=0.6.25=h5eee18b_0
  - aws-c-io=0.13.10=h5eee18b_0
  - aws-c-mqtt=0.7.13=h5eee18b_0
  - aws-c-s3=0.1.51=hdbd6064_0
  - aws-c-sdkutils=0.1.6=h5eee18b_0
  - aws-checksums=0.1.13=h5eee18b_0
  - aws-crt-cpp=0.18.16=h6a678d5_0
  - aws-sdk-cpp=1.10.55=h721c034_0
  - azure-core=1.29.5=py311h06a4308_0
  - black=24.3.0=py311h06a4308_0
  - blas=1.0=mkl
  - boost-cpp=1.82.0=hdb19cb5_2
  - bottleneck=1.3.7=py311hf4808d0_0
  - brotli-python=1.0.9=py311h6a678d5_7
  - bzip2=1.0.8=h5eee18b_5
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.3.11=h06a4308_0
  - cached-property=1.5.2=py_0
  - certifi=2024.6.2=py311h06a4308_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=py311h06a4308_0
  - comm=0.2.2=pyhd8ed1ab_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - dataclasses=0.8=pyhc8e2a94_3
  - datasets=2.19.0=py_0
  - debugpy=1.6.7=py311h6a678d5_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - dill=0.3.6=py311h06a4308_0
  - distro=1.9.0=py311h06a4308_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=2.0.1=pyhd8ed1ab_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py311h06a4308_0
  - flake8=7.0.0=py311h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - frozenlist=1.4.0=py311h5eee18b_0
  - fuzzywuzzy=0.18.0=py311h06a4308_0
  - gflags=2.2.2=h6a678d5_1
  - giflib=5.2.1=h5eee18b_3
  - glog=0.5.0=h6a678d5_1
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py311hc9b5ff0_0
  - gnutls=3.6.15=he1e5248_0
  - grpc-cpp=1.48.2=he1ff14a_1
  - h11=0.14.0=py311h06a4308_0
  - huggingface_hub=0.23.0rc1=py_0
  - icu=73.1=h6a678d5_0
  - idna=3.4=py311h06a4308_0
  - importlib-metadata=7.1.0=pyha770c72_0
  - importlib_metadata=7.1.0=hd8ed1ab_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.29.3=pyhd33586a_0
  - ipython=8.24.0=pyh707e725_0
  - isort=5.9.3=pyhd3eb1b0_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.3=py311h06a4308_0
  - jiter=0.5.0=py311h5ecf98a_0
  - jpeg=9e=h5eee18b_1
  - jsonlines=2.0.0=pyhd3eb1b0_2
  - jupyter_client=8.6.1=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py311h38be061_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libboost=1.82.0=h109eef0_2
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.9.0.20=0
  - libcurand=10.3.5.119=0
  - libcurl=8.5.0=h251f7ec_0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=13.2.0=h807b86a_5
  - libgomp=13.2.0=h807b86a_5
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=3.20.3=he621ea3_0
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.10.0=hdbd6064_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libthrift=0.15.0=h1795dd8_2
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.3=py311h5eee18b_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mccabe=0.7.0=pyhd3eb1b0_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py311h5eee18b_1
  - mkl_fft=1.3.8=py311h5eee18b_0
  - mkl_random=1.2.4=py311hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py311h06a4308_0
  - multidict=6.0.4=py311h5eee18b_0
  - multiprocess=0.70.14=py311h06a4308_0
  - mypy_extensions=1.0.0=py311h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py311h06a4308_0
  - numexpr=2.8.7=py311h65dcdc2_0
  - numpy=1.26.4=py311h08b1b3b_0
  - numpy-base=1.26.4=py311hf175353_0
  - omegaconf=2.3.0=pyhd8ed1ab_0
  - openai=1.35.5=pyhd8ed1ab_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.3.0=hd590300_0
  - orc=1.7.4=hb3bc3d3_1
  - packaging=23.2=py311h06a4308_0
  - pandas=2.2.1=py311ha02d727_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pathspec=0.10.3=py311h06a4308_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.0.1=py311ha6cbd5a_0
  - platformdirs=3.10.0=py311h06a4308_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - protobuf=3.20.3=py311h6a678d5_0
  - psutil=5.9.8=py311h459d7ec_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pyarrow=14.0.2=py311hb6e97c4_0
  - pyarrow-hotfix=0.6=pyhd8ed1ab_0
  - pycodestyle=2.11.1=py311h06a4308_0
  - pyflakes=3.2.0=py311h06a4308_0
  - pysocks=1.7.1=py311h06a4308_0
  - python=3.11.8=h955ad1f_0
  - python-levenshtein=0.12.2=py311h5eee18b_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python-xxhash=2.0.2=py311h5eee18b_1
  - python_abi=3.11=2_cp311
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.1=py311h5eee18b_0
  - pyzmq=25.1.2=py311h6a678d5_0
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py311h06a4308_1
  - responses=0.13.3=pyhd3eb1b0_0
  - s2n=1.3.27=hdbd6064_0
  - safetensors=0.4.2=py311h24d97f6_0
  - setuptools=68.2.2=py311h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.10=h6a678d5_1
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - sympy=1.12=pyh04b8f61_3
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=2.2.1=py311_cu118
  - tornado=6.4=py311h459d7ec_0
  - tqdm=4.65.0=py311h92b7b1e_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing-extensions=4.9.0=py311h06a4308_1
  - typing_extensions=4.9.0=py311h06a4308_1
  - urllib3=2.1.0=py311h06a4308_1
  - utf8proc=2.6.1=h5eee18b_1
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.41.2=py311h06a4308_0
  - xxhash=0.8.0=h7f8727e_3
  - xz=5.4.6=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.9.3=py311h5eee18b_0
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - absl-py==2.1.0
      - accelerate==0.21.0
      - aiofiles==23.2.1
      - altair==5.2.0
      - anyio==4.3.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - async-lru==2.0.4
      - attrs==23.2.0
      - autopep8==2.1.0
      - azure-ai-textanalytics==5.3.0
      - azure-common==1.1.28
      - azure-identity==1.16.0
      - azure-keyvault-secrets==4.8.0
      - azure-storage-blob==12.20.0
      - babel==2.15.0
      - beautifulsoup4==4.12.3
      - bitsandbytes==0.42.0
      - bleach==6.1.0
      - cffi==1.16.0
      - colorama==0.4.6
      - contourpy==1.2.0
      - cryptography==42.0.5
      - cycler==0.12.1
      - defusedxml==0.7.1
      - einops==0.6.1
      - einops-exts==0.0.4
      - fastapi==0.110.0
      - fastjsonschema==2.19.1
      - ffmpy==0.3.2
      - fonttools==4.49.0
      - fqdn==1.5.1
      - fsspec==2024.2.0
      - google-generativeai==0.7.0
      - gradio==4.16.0
      - gradio-client==0.8.1
      - httpcore==1.0.5
      - httpx==0.27.0
      - huggingface-hub==0.21.3
      - hydra-core==1.3.2
      - immutabledict==4.2.0
      - importlib-resources==6.1.2
      - isodate==0.6.1
      - isoduration==20.11.0
      - joblib==1.3.2
      - json5==0.9.25
      - jsonpointer==2.4
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.0
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.1
      - kiwisolver==1.4.5
      - langdetect==1.0.9
      - markdown-it-py==3.0.0
      - markdown2==2.4.13
      - matplotlib==3.8.3
      - mdurl==0.1.2
      - mistune==3.0.2
      - msal==1.28.0
      - msal-extensions==1.1.0
      - nltk==3.8.1
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - notebook==7.2.0
      - notebook-shim==0.2.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - orjson==3.9.15
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - peft==0.9.0
      - pip==24.0
      - portalocker==2.8.2
      - prometheus-client==0.20.0
      - protobuf==3.20.3
      - pycocotools==2.0.8
      - pycparser==2.22
      - pydantic==2.6.3
      - pydantic-core==2.16.3
      - pydub==0.25.1
      - pygments==2.17.2
      - pyjwt==2.8.0
      - pyparsing==3.1.1
      - python-dateutil==2.9.0.post0
      - python-json-logger==2.0.7
      - python-multipart==0.0.9
      - pytz==2024.1
      - referencing==0.33.0
      - regex==2023.12.25
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - ratelimit==2.2.1
      - rich==13.7.1
      - rpds-py==0.18.0
      - ruff==0.3.0
      - scikit-learn==1.2.2
      - scipy==1.12.0
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - send2trash==1.8.3
      - sentencepiece==0.1.99
      - shellingham==1.5.4
      - shortuuid==1.0.12
      - sniffio==1.3.1
      - soupsieve==2.5
      - starlette==0.36.3
      - svgwrite==1.4.3
      - terminado==0.18.1
      - threadpoolctl==3.3.0
      - timm==0.6.13
      - tinycss2==1.3.0
      - tokenizers==0.19.1
      - tomlkit==0.12.0
      - toolz==0.12.1
      - torch==2.1.2
      - torchvision==0.16.2
      - transformers==4.40.2
      - triton==2.1.0
      - typer==0.9.0
      - types-python-dateutil==2.9.0.20240316
      - tzdata==2024.1
      - uri-template==1.3.0
      - uvicorn==0.27.1
      - wavedrom==2.0.3.post3
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==11.0.3
